version: '1.0'

services:
  api:
    build: .
    container_name: task_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: #aunque el profe dijo que no lo respetaba
      db:
        condition: service_healthy
    networks:
      - task_network

  db:
    image: postgres:17-alpine
    container_name: task_db
    env_file:
      - .env
    volumes:
      - task_data:/var/lib/postgresql/data
    networks:
      - task_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 5s

networks:
  task_network:
    driver: bridge

volumes:
  task_data: